import { NextResponse, type NextRequest } from "next/server";

// Yoast's XML sitemaps and feeds are generated by WordPress; serve them
// through a route handler that rewrites the CMS address to the public one.
export function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl;
  if (/^\/[a-z0-9_-]*sitemap[a-z0-9_-]*\.(xml|xsl)$/i.test(pathname) || /^\/(.+\/)?feed\/?$/.test(pathname)) {
    const url = req.nextUrl.clone();
    url.pathname = "/api/wp-proxy";
    url.search = `?path=${encodeURIComponent(pathname)}`;
    return NextResponse.rewrite(url);
  }
}

export const config = {
  matcher: ["/((?!_next/|api/).*)"],
};
